# CTR-GCN
ctrgcn:
  train_data_args:
    random_choose: False
    random_shift: False
    random_move: False
    window_size: 64
    normalization: False
    random_rot: True
    p_interval: [0.5, 1]
    vel: False
    bone: False

  test_data_args:
    window_size: 64
    p_interval: [0.95]
    vel: False
    bone: False

  model: model.ctrgcn.Model
  model_args:
    num_class: 20
    num_point: 25
    num_person: 2
    graph: graph.ntu_rgb_d.Graph
    graph_args:
      labeling_mode: 'spatial'

# optim
  weight_decay: 0.0004
  lr: 0.1
  lr_factor: 0.1
  lr_patience: 35
  momentum: 0.9

# training
  batch_size: 64
  test_batch_size: 64
  nepochs: 65
  nesterov: True

# MS-G3D
msg3d:
  train_data_args:
    random_choose: False
    random_shift: False
    random_move: False
    window_size: 64
    normalization: False
    p_interval: [0.5, 1]
    vel: False
    bone: False

  test_data_args:
    window_size: 64
    p_interval: [0.95]
    vel: False
    bone: False

  model: model.msg3d.Model
  model_args:
    num_class: 20
    num_point: 25
    num_person: 2
    num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
    num_g3d_scales: 6
    graph: graph.ntu_rgb_d.AdjMatrixGraph

# optim
  weight_decay: 0.0005
  lr: 0.05
  lr_patience: 30

# training
  nepochs: 50
  batch_size: 32
  forward_batch_size: 16
  test_batch_size: 32
  nesterov: True
