# Task Args
task_args:
  num_tasks: 10
  cpertask: 2
  joints_to_mask: []
#  joints_to_mask: [24, 23, 22, 21, 19, 15]
#  joints_to_mask: [0, 12, 13, 14, 15, 16, 17, 18, 19]
  action_list: [18, 1, 19, 8, 10, 17, 6, 13, 4, 2, 5, 14, 9, 7, 16, 11, 3, 0, 15, 12]

# CTR-GCN
ctrgcn:
  test_data_args:
    window_size: 64
    p_interval: [0.95]
    vel: False
    bone: False

  model: model.ctrgcn.Model
  model_args:
    num_class: 20
    num_point: 25
    num_person: 2
    graph: graph.ntu_rgb_d.Graph
    graph_args:
      labeling_mode: 'spatial'

  test_batch_size: 64

# MS-G3D
msg3d:
  test_data_args:
    window_size: 64
    p_interval: [0.95]
    vel: False
    bone: False

  model: model.msg3d.Model
  model_args:
    num_class: 20
    num_point: 25
    num_person: 2
    num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
    num_g3d_scales: 6
    graph: graph.ntu_rgb_d.AdjMatrixGraph

  test_batch_size: 32
